"""The intervention contrast: the same representation, no leverage generically,
large leverage in the right dynamical state.

2 x 2, measured data only (no schematic):
  left column  — RESPOP (prereg 9bc745e): concept dosed at 4 GENERIC initial states.
    (a) z500 response RMS vs lead for all 10 concepts, against the measured numeric
        floor and the scrambled-label perm band. 0/10 detected (bar SNR >= 3).
    (c) the actual +24 h Δz500 response field for the strongest tropical concept
        (ascent): max |Δ| 0.6 m against synoptic anomalies of ~100 m.
  right column — the convection lever (RESULT_convection_lever.md): the SAME kind of
    SAE features ablated INSIDE a forming hurricane (restore-to-normal, 1500 km disk).
    (b) haishen2020 MSLP-minimum trajectories: baseline / restore-to-normal /
        delete-to-zero / firing-rate-matched random control, with ERA5 truth.
    (d) Δ-deepening for all seven storms + the non-developing control
        (results/skill/convection/verdict.json values, transcribed in
        RESULT_convection_lever.md; medians 2.794 / 0.013 hPa).

Needs cartopy -> python figures/paper_fig_contrast.py
"""
import sys
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import cartopy.crs as ccrs
import cartopy.feature as cfeature

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "figures"))
from paper_palette import BG, INK, MUTED, FAINT, GRIDC, BLUE, GREEN, YELLOW, GREY, PALE  # noqa

PC = ccrs.PlateCarree()
INPUTS = ROOT / "results/fs_contrast_inputs.npy"


def build_inputs():
    """One-off: compact bundle (~2.6 MB) from the 51 MB results/fs_respop.npy (not shipped;
    regenerated by `python -m graphcast_sae.concepts.respop`).
    Keeps the response-RMS table and only the COARSE slice panel (c) draws: every arm at
    the first lead (+6 h), z500 field, on the 1.5-degree grid."""
    R = np.load(ROOT / "results/fs_respop.npy", allow_pickle=True).item()
    out = {k: R[k] for k in ("RMS", "arms", "names", "fields", "S", "prereg")}
    out["COARSE_lead0_z500"] = np.asarray(R["COARSE"][:, 0, 0], np.float32)  # (22, 120, 240)
    np.save(INPUTS, out, allow_pickle=True)
    return out
COAST = "#a8a8a8"

# Δ-deepening (hPa), restore-to-normal vs firing-rate-matched random control.
# Source: results/skill/convection/verdict.json, as published in RESULT_convection_lever.md.
STORMS = [("haiyan 2013", 7.516, -0.156), ("haishen 2020", 7.474, -0.115),
          ("wilma 2005", 4.382, -0.119), ("ida 2021", 2.794, 0.050),
          ("goni 2020", 2.146, 0.370), ("michael 2018", 2.145, 0.158),
          ("patricia 2015", 0.203, 0.013)]
NONDEV = ("non-developing wave (control)", -0.010, None)


def main():
    R = np.load(INPUTS, allow_pickle=True).item() if INPUTS.exists() else build_inputs()
    RMS, arms, fields = R["RMS"], R["arms"], R["fields"]
    iz = fields.index("z500")
    leads = np.arange(1, R["S"] + 1) * 6
    m = RMS.mean(0)                                   # (22 arms, 10 leads, 9 fields)
    floor = m[[arms.index("nf0"), arms.index("nf1")], :, iz].mean(0)
    perm = m[[arms.index(f"perm{i}") for i in range(10)], :, iz]
    conc = {nm: m[arms.index(nm), :, iz] for nm in R["names"]}
    C = R["COARSE_lead0_z500"]

    H = np.load(ROOT / "results/skill/convection/run_haishen2020.npy",
                allow_pickle=True).item()
    tr = {a: np.asarray(H["res"][a]["mslp_min"]) for a in H["res"]}
    era = np.load(ROOT / "results/skill/convection/era5_truth.npy",
                  allow_pickle=True).item()["haishen2020"]
    tlead = np.arange(16) * 6 + 6                      # forecast valid times, +6..+96 h

    fig = plt.figure(figsize=(12.2, 7.8), facecolor=BG)
    gs = gridspec.GridSpec(2, 2, height_ratios=[1.0, 1.0], width_ratios=[1, 1],
                           hspace=0.44, wspace=0.26, left=0.075, right=0.975,
                           top=0.86, bottom=0.075)
    fig.text(0.075, 0.965, "Generic initial states — concept dose",
             fontsize=12, color=INK, weight="bold")
    fig.text(0.555, 0.965, "Hurricane regime — convection ablation",
             fontsize=12, color=INK, weight="bold")
    fig.text(0.075, 0.935, "impulse γ=1.0 on 4 seasonal ICs; free 60 h roll",
             fontsize=8.5, color=MUTED)
    fig.text(0.555, 0.935, "restore-to-normal in a 1500 km disk; free 96 h roll",
             fontsize=8.5, color=MUTED)

    # ---------------- (a) RESPOP response vs lead ----------------
    ax = fig.add_subplot(gs[0, 0])
    ax.fill_between(leads, perm.mean(0) - perm.std(0), perm.mean(0) + perm.std(0),
                    color=PALE, alpha=0.55, lw=0, zorder=1,
                    label="scrambled-label groups (10 perm arms, ±1 sd)")
    for i, (nm, v) in enumerate(conc.items()):
        ax.plot(leads, v, color=BLUE, lw=1.0, alpha=0.65, zorder=3,
                label="10 dosed concepts" if i == 0 else None)
    ax.plot(leads, floor, color=INK, lw=1.4, ls=":", zorder=4,
            label="numeric floor (unpatched roll)")
    ax.set_xlabel("lead (h)", fontsize=9, color=MUTED)
    ax.set_ylabel("z500 response RMS (m)", fontsize=9, color=MUTED)
    ax.set_xlim(6, 60); ax.set_ylim(0, 0.75)
    ax.legend(loc="upper left", fontsize=7.6, frameon=False)
    ax.text(59, 0.06, "0/10 DETECTED (bar SNR ≥ 3)\nresponse ≈ floor, "
            "indistinguishable from perm", fontsize=8, color=MUTED, ha="right")
    ax.set_title("a   Response magnitude: at the noise floor", fontsize=10.5,
                 color=INK, weight="bold", loc="left", pad=6)

    # ---------------- (b) haishen trajectories ----------------
    ax = fig.add_subplot(gs[0, 1])
    ax.plot(tlead, tr["baseline"], color=BLUE, lw=1.9, label="baseline forecast",
            zorder=4)
    ax.plot(tlead, tr["rand-normal"], color=GREY, lw=1.3, ls=(0, (3, 2)),
            label="random group → normal (control)", zorder=3)
    ax.plot(tlead, tr["conv-normal"], color=YELLOW, lw=1.9,
            label="convection → normal", zorder=5)
    ax.plot(tlead, tr["conv-zero"], color=YELLOW, lw=1.2, ls=(0, (3, 2)),
            label="convection → zero", zorder=4)
    ne = min(len(tlead), len(np.asarray(era["mslp_min"])) - 1)
    ax.plot(tlead[:ne], np.asarray(era["mslp_min"])[1:1 + ne], color=INK, lw=1.0,
            ls=":", label="ERA5 truth", zorder=2)
    ib, ic_ = np.argmin(tr["baseline"]), np.argmin(tr["conv-normal"])
    ax.annotate("", xy=(tlead[ic_], tr["conv-normal"][ic_]),
                xytext=(tlead[ic_], tr["baseline"][ib]),
                arrowprops=dict(arrowstyle="<->", color=INK, lw=0.9))
    ax.text(tlead[ic_] + 1.5, (tr["conv-normal"][ic_] + tr["baseline"][ib]) / 2,
            "Δ-deepening\n+7.5 hPa", fontsize=8, color=INK, va="center")
    ax.set_xlabel("lead (h)", fontsize=9, color=MUTED)
    ax.set_ylabel("storm-box MSLP minimum (hPa)", fontsize=9, color=MUTED)
    ax.set_xlim(6, 96)
    ax.legend(loc="lower left", fontsize=7.6, frameon=False)
    ax.set_title("b   haishen 2020: the forecast loses a third of its deepening",
                 fontsize=10.5, color=INK, weight="bold", loc="left", pad=6)

    # ---------------- (c) RESPOP response field ----------------
    ax = fig.add_subplot(gs[1, 0], projection=PC)
    ia = arms.index("ascent")
    F = C[ia]                          # +6 h (lead of max SNR), z500, 1.5-degree grid
    vm = 0.6
    im = ax.imshow(F, origin="lower", extent=[-180, 180, -90, 90], cmap="RdBu_r",
                   vmin=-vm, vmax=vm, transform=PC, interpolation="bilinear")
    ax.add_feature(cfeature.COASTLINE.with_scale("110m"), edgecolor=COAST,
                   linewidth=0.4)
    ax.set_global(); ax.set_xticks([]); ax.set_yticks([])
    for sp in ax.spines.values():
        sp.set_edgecolor(INK); sp.set_linewidth(0.5)
    cb = plt.colorbar(im, ax=ax, shrink=0.75, pad=0.02)
    cb.set_label("Δz500 (m) at +6 h", fontsize=8, color=MUTED)
    cb.ax.tick_params(labelsize=7, colors=MUTED)
    ax.set_title("c   Ascent concept, mean response field at max SNR (+6 h):\n"
                 "     max |Δz500| 1.1 m against ±100–200 m synoptic anomalies;\n"
                 "     A50 0.02 — half the response in 2% of the globe, then float noise",
                 fontsize=10, color=INK, weight="bold", loc="left", pad=6)

    # ---------------- (d) per-storm Δ-deepening ----------------
    ax = fig.add_subplot(gs[1, 1])
    names = [s[0] for s in STORMS] + [NONDEV[0]]
    yy = np.arange(len(names))[::-1]
    for y, (nm, dv, rv) in zip(yy, STORMS + [NONDEV]):
        ax.plot([0, dv], [y, y], color=GRIDC, lw=0.8, zorder=1)
        ax.scatter([dv], [y], s=46, color=YELLOW if dv > 0.1 else GREY, zorder=4,
                   edgecolors=INK, linewidths=0.4)
        if rv is not None:
            ax.scatter([rv], [y], s=26, facecolors="none", edgecolors=GREY,
                       linewidths=1.2, zorder=3)
    ax.axvline(0, color=PALE, lw=0.9, zorder=0)
    ax.axvline(2.794, color=YELLOW, lw=1.0, ls=(0, (4, 3)), zorder=2)
    ax.text(2.9, len(names) - 0.85, "median +2.79 hPa", fontsize=8, color=INK)
    ax.scatter([], [], s=46, color=YELLOW, edgecolors=INK, linewidths=0.4,
               label="convection → normal")
    ax.scatter([], [], s=26, facecolors="none", edgecolors=GREY, linewidths=1.2,
               label="random control (median +0.01)")
    ax.legend(loc="lower right", fontsize=7.8, frameon=False)
    ax.set_yticks(yy); ax.set_yticklabels(names, fontsize=8.2, color=INK)
    ax.set_xlim(-0.8, 8.3)
    ax.tick_params(axis="x", labelsize=8, colors=MUTED, length=0)
    ax.set_xlabel("Δ-deepening cost of the ablation (hPa, 96 h)", fontsize=9,
                  color=MUTED)
    ax.grid(axis="x", color=GRIDC, lw=0.5, zorder=0)
    ax.set_title("d   Seven storms: the lever is specific and event-locked",
                 fontsize=10.5, color=INK, weight="bold", loc="left", pad=6)
    for a in fig.axes:
        if a.name != "rectilinear":
            continue
        for sp in ("top", "right"):
            a.spines[sp].set_visible(False)
        for sp in ("left", "bottom"):
            a.spines[sp].set_color(PALE)

    for ext in ("png", "pdf"):
        fig.savefig(ROOT / f"figures/paper_fig_contrast.{ext}",
                    dpi=300 if ext == "png" else None, facecolor=BG,
                    bbox_inches="tight")
    print("-> figures/paper_fig_contrast.png / .pdf")


if __name__ == "__main__":
    main()
